### ISSUE TITLE
Incomplete list of repositories for gitea

### ISSUE THREAD

**Issue by hpodhaisky** [git-touch/git-touch#103]
Hi,

the list of my personal, private repositories for my gitea server displays only 30 out of my 82 repositories and I haven‘t found a way to access the missing ones with git-touch. I don’t understand the order in which this list is presented. Moreover, under „me“ collaborative repositories are listed, too. The views are identical under Android and iOS. The web interface of gitea works well.

**Comment by pd4d10** [comment]
Hi, @hpodhaisky , it should have been fixed in the latest v1.5.1.

Closing, feel free to reopen it if there are other problems.

**Comment by hpodhaisky** [comment]
Hi, @pd4d10 , thanks it is better now: (in v1.5.1 under Android) I can only see my repositories under "me". But still only 30. I could live with 30 if there were an option to filter. Alternatively, a simple fix (for me) would just be to increase 30 to 100.

I believe the reason is the default of DEFAULT_PAGING_NUM=30 in https://docs.gitea.io/en-us/config-cheat-sheet/ .

Thus, git-touch needs the option to fetch more than one page.
