### ISSUE TITLE
Add new platform: Gitee

### ISSUE THREAD

**Issue by pd4d10** [git-touch/git-touch#118]
https://gitee.com/

**Comment by shreyas1599** [comment]
Hi @pd4d10, 
I'm trying to add the issue screen. Need some help.
`IssueItem` takes a required parameter called [number](https://github.com/git-touch/git-touch/blob/c6757c154890b9120848d985229f80c7c842fbfd/lib/widgets/issue_item.dart#L37) but gitee issue numbers are not integers. They look something like this: `#I2BRYV`. Which of these would you suggest or is there an alternative apart from this?

- Should I update `IssueItem` and make `number` as a `String` and update this across everything?
- Should I use the `id` parameter of the response (this is an integer) for now?

**Comment by pd4d10** [comment]
Well, it seems just used as a title.

Perhaps replace the `number` prop with a `title`?

**Comment by shreyas1599** [comment]
`title` prop already exists. Do you mean remove the `number` prop and append the issue number to title?

**Comment by pd4d10** [comment]
Oh, sorry, I missed that. It seems like a subtitle.

**Comment by pd4d10** [comment]
> append the issue number to title

It's a good idea, but I've noticed that the style is a little different with the title and wrapped with a `TextSpan`.

How about replacing it with `String subtitle`?

**Comment by shreyas1599** [comment]
> How about replacing it with `String subtitle`?

Alright I'll do this

**Comment by pd4d10** [comment]
This issue could be closed since Gitee is already supported. Let's track the features and bugs of Gitee with new issues.

**Comment by shreyas1599** [comment]
@pd4d10 going off-track here but can you enable [`Discussions`](https://docs.github.com/en/free-pro-team@latest/discussions/quickstart) on the repo(you're the admin)? It's for general discussions that may not necessarily be an issue. I opened it on my fork and it looks something like this:
![image](https://user-images.githubusercontent.com/28999492/103787009-16d56400-5063-11eb-9404-19a50b2c8cd8.png)

**Comment by pd4d10** [comment]
Enabled. I haven't used it before. Let's try it!
