### ISSUE TITLE
Chinese characters and emojis in descriptions are being decoded incorrectly in trending page

### ISSUE THREAD

**Issue by maxloh** [git-touch/git-touch#120]
See the screenshots below.

The Chinese characters in labuladong/fucking-algorithm description and the :books: emoji in EbookFoundation/free-programming-books description are being decoded incorrectly.

![Screenshot_20201017-134524](https://user-images.githubusercontent.com/35831069/96329440-6ec18780-107f-11eb-85e9-afc2ab9baf28.png)

![Screenshot_20201017-134527](https://user-images.githubusercontent.com/35831069/96329607-46d32380-1081-11eb-9834-f61f41171807.png)

![Screenshot_20201017-134538](https://user-images.githubusercontent.com/35831069/96329447-74b76880-107f-11eb-94b1-61b26073b72a.png)

**Comment by pd4d10** [comment]
Does this issue still exist?

**Comment by maxloh** [comment]
> Does this issue still exist?

No. Thanks for your awesome work. :)

**Comment by pd4d10** [comment]
OK, actually I'm not sure what causes this issue. One possible reason is that the character encoding returned by the API is not correct.

Closing. Feel free to reopen it if it happens next time

**Comment by pd4d10** [comment]
![IMG_BC7F30FA9C92-1](https://user-images.githubusercontent.com/9524411/99091348-b7cb1400-260a-11eb-875c-081643dd8eae.jpeg)
