### ISSUE TITLE
github user screen error

### ISSUE THREAD

**Issue by pd4d10** [git-touch/git-touch#122]
Seems to be a bug of the GraphQL API. The `color` should be a hex number

![image](https://user-images.githubusercontent.com/9524411/97576579-4d6e7d00-1a29-11eb-8b59-6e185685ab4a.png)

**Comment by pd4d10** [comment]
https://github.community/t/graphql-api-contribution-colors-breaking-change/140855

**Comment by pd4d10** [comment]
Temporarily fixed by a tricky way

**Comment by BinaryMuse** [comment]
I believe this should be resolved in the API now! Apologies for the issue
