### ISSUE TITLE
markdown rendering causes reboot

### ISSUE THREAD

**Issue by kakolisgay** [git-touch/git-touch#123]
Samsung Galaxy S8, Android 9, One UI

Opening this repo by going through settings crashes Android and causes a soft reboot. Issue was not present in previous play release

**Comment by kakolisgay** [comment]
This also seems to happen with my own repos, although testing is a bit of a pain

**Comment by pd4d10** [comment]
The latest version uses [webview_flutter](https://pub.dev/packages/webview_flutter) to display readmes. Probably related to this change.

**Comment by pd4d10** [comment]
Hi, @kakolisgay ,  you could select Markdown render engine in the latest version v1.9.0, which has been published and in review.

![simulator_screenshot_9F696016-7303-4A3B-9EBE-082B2F6AE396](https://user-images.githubusercontent.com/9524411/98466630-a0a3b500-220b-11eb-8c54-173842b117dc.png)

**Comment by kakolisgay** [comment]
Updated to 1.7.0 and strangely enough, it no longer crashes. Even in flutter rendering mode. Webview rendering mode doesn't seem to work though. Was the crash fixed upstream?

**Comment by pd4d10** [comment]
Markdown render engine history:

- v1.7.0 and before: flutter 
- v1.8.0: webview
- v1.9.0: two options: flutter and webview, default to webview

**Comment by kakolisgay** [comment]
Still not entire sure what was causing the crashes but I assume it was likely fixed upstream. Closing for now

**Comment by pd4d10** [comment]
```sh
E/flutter (27924): #46     MultiChildLayoutDelegate.layoutChild
package:flutter/…/rendering/custom_layout.dart:171
E/flutter (27924): #47     _ScaffoldLayout.performLayout
package:flutter/…/material/scaffold.dart:498
E/flutter (27924): #48     MultiChildLayoutDelegate._callPerformLayout
package:flutter/…/rendering/custom_layout.dart:243
E/flutter (27924): #49     RenderCustomMultiChildLayoutBox.performLayout
package:flutter/…/rendering/custom_layout.dart:402
E/flutter (27924): #50     RenderObject._layoutWithoutResize
package:flutter/…/rendering/object.dart:1634
E/flutter (27924): #51     PipelineOwner.flushLayout
package:flutter/…/rendering/object.dart:884
E/flutter (27924): #52     RendererBinding.drawFrame
package:flutter/…/rendering/binding.dart:436
E/flutter (27924): #53     WidgetsBinding.drawFrame
package:flutter/…/widgets/binding.dart:914
E/flutter (27924): #54     RendererBinding._handlePersistentFrameCallback
package:flutter/…/rendering/binding.dart:302
E/flutter (27924): #55     SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1117
E/flutter (27924): #56     SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1055
E/flutter (27924): #57     SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:971
E/flutter (27924): #58     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (27924): #59     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (27924): #60     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (27924): #61     _invoke (dart:ui/hooks.dart:251:10)
E/flutter (27924): #62     _drawFrame (dart:ui/hooks.dart:209:3)
```

**Comment by pd4d10** [comment]
It seems happen again at v1.10.0

**Comment by pd4d10** [comment]
It is probably caused by the webview component. Selecting 'Flutter' markdown render engine would solve this temporarily.

**Comment by ThisNekoGuy** [comment]
Still happens for me with webview*

**Comment by Lehmaning** [comment]
The problem still exists. Maybe we should open this issue again...
