### ISSUE TITLE
Restrict Access pls

### ISSUE THREAD

**Issue by Schokokex** [git-touch/git-touch#133]
I dont log in to this app. I dont like to give read and write to all my repos

**Comment by pd4d10** [comment]
Hi, @Schokokex , do you mean the private GitHub repos?

If you login via access token, it could be solved by checking `public_repo` instead of the `repo` group.

![image](https://user-images.githubusercontent.com/9524411/106351107-1902a980-6315-11eb-8df9-a89729fad10c.png)

**Comment by pd4d10** [comment]
> do you mean the private GitHub repos

A public repos only login option was added, which will be available at the next release.
