### ISSUE TITLE
Enable Null Safety feature

### ISSUE THREAD

**Issue by pd4d10** [git-touch/git-touch#136]
https://github.com/dart-lang/language/issues/110

**Comment by shreyas1599** [comment]
We should migrate `flutter_highlight` `flutter_vector_icons` `github_trending` `nanoid` `file_icon` first. I'll take a look and start opening PRs in them.

<img width="803" alt="image" src="https://user-images.githubusercontent.com/28999492/106789718-a4af6980-6678-11eb-962b-fe9c87fce0e1.png">
