### ISSUE TITLE
gitee: getting all commits of a specific branch

### ISSUE THREAD

**Issue by shreyas1599** [git-touch/git-touch#151]
Hi @pd4d10, I'm trying to add branches to `gitee`. This is all I could find for getting commits for a single branch:

[`Getting a single branch`](https://gitee.com/api/v5/swagger#/getV5ReposOwnerRepoBranchesBranch) - returns a response that only includes the most recent commit - [`Example Response`](https://gitee.com/api/v5/repos/shreyas1599/test/branches/master) is supposed to return 2 commits.  It does not return a list. I might've missed something. Perhaps you could help.

**Comment by pd4d10** [comment]
https://gitee.com/api/v5/swagger#/getV5ReposOwnerRepoBranches

This should be the "getting all branches" API

**Comment by shreyas1599** [comment]
> https://gitee.com/api/v5/swagger#/getV5ReposOwnerRepoBranches
> 


Oh no, this one I got. I mean all commits for a single branch. After selecting a particular brand the commits screen should display all commits specific to that branch right?

**Comment by pd4d10** [comment]
Oh, sorry, didn't see it clearly 😂.

Does [this API](https://gitee.com/api/v5/swagger#/getV5ReposOwnerRepoCommits) work? It seems to have a `sha` parameter to specify the branch

**Comment by shreyas1599** [comment]
> Does [this API](https://gitee.com/api/v5/swagger#/getV5ReposOwnerRepoCommits) work? It seems to have a `sha` parameter to specify the branch

Ah ok I didn't notice the parameters. I was only searching the endpoints. I'll try this.
