### ISSUE TITLE
Issue: Not able to view Organizations

### ISSUE THREAD

**Issue by Lukas-Batema** [git-touch/git-touch#162]
When I am on the “Me” tab, and click on the “Organizations” button, it shows that I don’t have an organization, even though I actually do. Currently, it says it is empty. This is related to this [closed issue](https://github.com/git-touch/git-touch/issues/25). Thank you!

Best Wishes,
          Lukas Batema

**Comment by pd4d10** [comment]
Thanks for the report. which login entry do you use, OAuth2 or access token?

**Comment by Lukas-Batema** [comment]
I use OAuth2 @pd4d10 

> Thanks for the report. which login entry do you use, OAuth2 or access token?

**Comment by pd4d10** [comment]
The API used in this case is [here](https://docs.github.com/en/rest/reference/orgs#list-organizations-for-a-user): `https://api.github.com/users/{your_username}/orgs`

**Comment by Lukas-Batema** [comment]
Dear @pd4d10,
I think the issue is fixed. Now it shows a non-stop blue refresh spinner under the visible organization. Thanks for your help!

Best Wishes,
Lukas Batema

**Comment by pd4d10** [comment]
Closing. Feel free to reopen it if there are other problems
