### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [git-touch/git-touch#163]
You can add Screenshots for F-Droid, too, if you want.
https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/
https://gitlab.com/snippets/1895688
That was simply information about what is still possible. You would then only have to enter the screenshots in fastlane.

**Comment by linsui** [comment]
This should be very easy. I'm not sure which method is prefered. If those images in assets are only used for readme then we can move them to fastlane.

**Comment by mondlicht-und-sterne** [comment]
how " which method is preferred ?

**Comment by linsui** [comment]
We can also copy them to fastlane.

**Comment by mondlicht-und-sterne** [comment]
with fastlane this should work.

**Comment by shreyas1599** [comment]
[This](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/) link has three directories - `phoneScreenshots`, `tenInchScreenshots` and `sevenInchScreenshots`. Should I add relevant images to all these directories or is `phoneScreenshots` enough?

**Comment by linsui** [comment]
`phoneScreenshots` is enough.
