### ISSUE TITLE
Git Touch can't open github or other clickable links from apps, please fix that. Also add codeberg.org support 

### ISSUE THREAD

**Issue by User1l0** [git-touch/git-touch#164]

**Comment by shreyas1599** [comment]
@User1l0 codeberg is built on top of gitea. You can use codeberg on the app by logging in with `Gitea`. Just make sure you change the domain name to `https://codeberg.org`

![image](https://user-images.githubusercontent.com/28999492/104838615-1732f200-58e2-11eb-8f02-887e69f57073.png)

**Comment by shreyas1599** [comment]
@pd4d10 should I add a separate item called `Codeberg` below [this](https://github.com/git-touch/git-touch/blob/c75288ef977ae84123afc6ed7a1efd2527cc859a/lib/screens/login.dart#L335) and re-use `loginToGitea` and perhaps modify readme to indicate support for Codeberg?

**Comment by pd4d10** [comment]
Is this Codeberg's API exactly the same as Gitea?

If so, in my opinion, it's not necessary to add a new one. Perhaps add a note under the Gitea login inputs?

**Comment by shreyas1599** [comment]
Yeah codeberg api redirects to the gitea api page. Alright, then I'll add a note

**Comment by pd4d10** [comment]
The deep links issue is probably related to https://github.com/git-touch/git-touch/issues/60
