### ISSUE TITLE
Add Dependabot dependability score to README.md

### ISSUE THREAD

**Issue by Lukas-Batema** [git-touch/git-touch#167]
Dear GitTouch Developers,
It would be nice, if we could see if the GitHub Actions were passing, how dependable the code is, and how many security issues are currently in the code.

Best Wishes,
Lukas Batema

**Comment by shreyas1599** [comment]
Do you mean [this](https://github.com/marketplace/dependabot-preview)? If so, dart is not supported.

**Comment by Lukas-Batema** [comment]
> Do you mean [this](https://github.com/marketplace/dependabot-preview)? If so, dart is not supported.

Yes, I mean that. I guess I will close this issue then ;)
