### ISSUE TITLE
Missing parts in github

### ISSUE THREAD

**Issue by Thewisem** [git-touch/git-touch#174]
I would like for you to add releases which are available on github. Currently I don't see an option on gitlab that lets me check the releases of the software or app

**Comment by pd4d10** [comment]
Thanks for your feedback!

Do you mean there should be a place in the app (maybe a button) to check if there is a new release?

**Comment by shreyas1599** [comment]
I did something like this for now (does not display all assets. On click downloads the first downloadable asset. I'm thinking of adding all the assets). Releases tab is in the repo screen.

![IMG_20210130_135747_777.jpg](https://user-images.githubusercontent.com/28999492/106351583-3fb7e480-6303-11eb-8870-affc52fda8fc.jpg)

**Comment by Thewisem** [comment]
Yes. Exactly what you said. A button for releases. :)

**Comment by Thewisem** [comment]
Try to show the changes they told they made in public in each release and each release itself. This way we can download directly from github. Sorry about the late response. Don't mind about the external download. The releases and publishes button should be there

**Comment by Thewisem** [comment]
It would help in not using my account on my browser and use my account on two gits soooo yeah. :).

**Comment by pd4d10** [comment]
Actually, there is an entry for releases, which may be a little hidden:

It just directs to the web version. It would be more native with #179

![simulator_screenshot_345850E6-5491-41F9-9CBB-B5B1650FED75](https://user-images.githubusercontent.com/9524411/106374782-f75efc00-63c0-11eb-9dcc-93f54de16a7d.png)

**Comment by shreyas1599** [comment]
@pd4d10 I noticed the following a while back too. Recalled after seeing this image.

I had added icons for some of them but there's repetition in the use of icons and I used icons that don't exactly match the action. Are there any other icon packs? Or are there icons that come in a variety of filled colours(not just the different colour outlines, but the entire icon being filled). It would be good to use different colours in a single page. For example, one the repo page, it would be good to give a different colour for each of the tab

**Comment by pd4d10** [comment]
The Octicons we are using is v1 (from flutter_vector_icon). It seems [v2](https://primer.style/octicons/) is released for a while, which is landed in the GitHub web page

Perhaps we should upgrade to v2 too

**Comment by shreyas1599** [comment]
You mean modifying [this](https://github.com/pd4d10/flutter-vector-icons/blob/master/lib/src/octicons.dart) right? How did you get the icon data to create the file?

**Comment by pd4d10** [comment]
> You mean modifying this right

This package is supposed to be a port of [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons). Looks like the upstream package has no upgrade plan to octicons v2, so perhaps we should make it our own.

BTW, I just pushed a commit to `main` to replace most of the icons with [ionicons](https://ionicons.com/). The best of it is that every icon has an outline version, which is really useful for indicating active/not active

> How did you get the icon data to create the file

The `react-native-vector-icons` lib uses [fontcustom](https://github.com/oblador/react-native-vector-icons/blob/master/scripts/octicons.sh) to convert SVGs to icon font.

**Comment by shreyas1599** [comment]
> BTW, I just pushed a commit to main to replace most of the icons with ionicons.

Ah yes I noticed this in the screenshot you posted on the issue you opened a while ago. Looks better too imo.
