### ISSUE TITLE
github releases page error with cupertino scaffold

### ISSUE THREAD

**Issue by pd4d10** [git-touch/git-touch#181]
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-02-01 at 23 17 41](https://user-images.githubusercontent.com/9524411/106478004-bc091e00-64e3-11eb-8760-ff26be977186.png)

**Comment by shreyas1599** [comment]
Oops. I tested it on Cupertino only. I'll check it out and fix it by tomorrow night.
