### ISSUE TITLE
GitHub files page error

### ISSUE THREAD

**Issue by shreyas1599** [git-touch/git-touch#182]
I noticed this a while back. Forgot to get to it. Opening an issue in case I forget again.

![Screenshot_20210201-205829.png](https://user-images.githubusercontent.com/28999492/106479718-a1797980-64d0-11eb-8598-2ce14a061cfa.png)

**Comment by shreyas1599** [comment]
This seems to be a problem of `HighlightView`. [This](https://github.com/git-touch/highlight/blob/251505aae568e95ad941e023c110495fa5ad0a16/flutter_highlight/lib/flutter_highlight.dart#L37) is the offending line. When `patch` is null as is the case with the above screenshot, the error occurs.

**Comment by shreyas1599** [comment]
I can catch it in `files_item.dart` itself but I think it would be better for the package to handle null.

**Comment by shreyas1599** [comment]
I'm thinking of replacing [this line](https://github.com/git-touch/git-touch/blob/918d0f3971b80fba411143a6bf1d3705eb1e4abb/lib/widgets/files_item.dart#L44) with `patch ?? "No text to be shown here"` or should I just leave it as an empty string. I think the first option is better because github returns a null patch only if the file has binary data. What do you think @pd4d10 ?

**Comment by pd4d10** [comment]
OK. I have no strong preference for this, as long as it is easy to understand for users.
