### ISSUE TITLE
Support browsing without login

### ISSUE THREAD

**Issue by linsui** [git-touch/git-touch#192]
Could you please support using this app without accounts? Thanks!

**Comment by shreyas1599** [comment]
Unfortunately I don't think GitHub allows this. To use their api, the user has to be authenticated

**Comment by linsui** [comment]
> Unauthenticated clients can make 60 requests per hour. To get more requests per hour, we'll need to authenticate. In fact, doing anything interesting with the GitHub API requires authentication.

Yep. I got it.
