### ISSUE TITLE
Crashing Hard

### ISSUE THREAD

**Issue by MrEPOZ** [git-touch/git-touch#194]
Browsing around the settings its fine but as soon I open a stared item the app restarts the phone( straight to Samsung logo). Phone is Note 8/Android 9 and app version is 1.10.1

**Comment by pd4d10** [comment]
Thanks for the feedback!

> open a stared item

Does this mean one of your starred repositories? Could you please provide the repo's owner and name?

**Comment by MrEPOZ** [comment]
Yes, on my stared repos. On all of them, funny enough even on this one to.

**Comment by pd4d10** [comment]
Probably related to #132 

Let's track it there
