### ISSUE TITLE
Grey screen on iOS

### ISSUE THREAD

**Issue by adrianjagielak** [git-touch/git-touch#199]
Hi, I tried to install it but the only thing I see is a static gray screen.

iOS 14.2 iPhone XS Max, GitTouch 1.12.0 from the App Store

![image](https://user-images.githubusercontent.com/21083675/108428813-7072a600-723f-11eb-944e-0c59e7b3bade.png)

**Comment by pd4d10** [comment]
Looks weird. Is this the first screen after opening the app without doing anything?

**Comment by thomas-bouvier** [comment]
Hi, I get the exact same screen on Android since release 1.12.0. The white splash screen (with the logo on it) loads and disappears before that.

**Comment by miracle091** [comment]
> 
> 
> Looks weird. Is this the first screen after opening the app without doing anything?

Same on LineageOS 17.1, version 1.12.0 but installed trough apk (cause this version. is not available on f-droid at the time). This not happen with the 1.11.1 and if this could help, build directly from source work normally.

**Comment by shreyas1599** [comment]
I think the error is because of [this](https://github.com/git-touch/git-touch/blob/4a7028f5256fde36a951f09b6c88e2f420e77e79/pubspec.yaml#L35). While trying to build this error is returned:
```
Because every version of flutter_localizations from sdk depends on intl 0.17.0 and git_touch depends on intl ^0.16.0, flutter_localizations from sdk is forbidden.

So, because git_touch depends on flutter_localizations any from sdk, version solving failed.
pub get failed (1; So, because git_touch depends on flutter_localizations any from sdk, version solving failed.)
```

I changed it to 0.17.0 and created a release on my local and it seems to work fine. @pd4d10 can you verify this on your machine?

**Comment by pd4d10** [comment]
0.17.0 seems to be a null safety version: https://pub.dev/packages/intl/versions/0.17.0

Have you set your Flutter channel other than `stable` (for example `beta`)?

**Comment by pd4d10** [comment]
I guess it may be caused by the system default locale. 

@adrianjagielak @thomas-bouvier @miracle091 Could you please post your system default locale here? Thanks!

**Comment by pd4d10** [comment]
Update: This is exactly the reason that causes this problem

![simulator_screenshot_63B4E58E-CA9C-415C-A001-481DDC48981F](https://user-images.githubusercontent.com/9524411/108506438-bdb04f80-72f3-11eb-908a-f87a5dc43c35.png)

**Comment by pd4d10** [comment]
Landed a new release: https://github.com/git-touch/git-touch/releases/tag/v1.12.2

iOS package is waiting for review and should be ready in 24h.
