### ISSUE TITLE
Wrong app language

### ISSUE THREAD

**Issue by linsui** [git-touch/git-touch#206]
My system language is Simplified Chinese but the app language is set as English when following system. Thanks!

**Comment by pd4d10** [comment]
Fixed in 74e731af5ed5242c0852c12f859d0cd16a6c3c94

Will land in the next release soon.

**Comment by linsui** [comment]
Thanks!

**Comment by pd4d10** [comment]
Fixed in the latest release: https://github.com/git-touch/git-touch/releases/tag/v1.12.3
