### ISSUE TITLE
Inconsist strings

### ISSUE THREAD

**Issue by linsui** [git-touch/git-touch#207]
In Settings/SYSTEM, `GitHub status` and `Switch accounts` are used instead of `GitHub Status` and `Switch Accounts`. Is that intended?

**Comment by pd4d10** [comment]
Not quite sure. Is it a convention to capitalize the first letter of all words in English displays?

If yes, then it's better to correct it

**Comment by linsui** [comment]
I don't know, but I thought that those strings should be in the same format. Could you please choose a prefered format and correct inconsist ones?

**Comment by shreyas1599** [comment]
I checked a few apps. They either follow all first letters capitalized or only the first letter of the string capitalized. In git touch some are only first letter capitalized while some are first letter of every word capitalised. Better to make it consistent. I'll make first letter of every word capitalised

**Comment by Lukas-Batema** [comment]
> Not quite sure. Is it a convention to capitalize the first letter of all words in English displays?
> 
> 
> 
> If yes, then it's better to correct it

Yes, if they are in a title, which this is, I assume, or a proper noun. Only one needs to be fulfilled, for this to be capitalized.
