### ISSUE TITLE
WebView as a Markdown Engine crashes app

### ISSUE THREAD

**Issue by gitsbi** [git-touch/git-touch#210]
If I use WebView as the Markdown Render Engine (which was preset) the app crashes when I try to view https://github.com/gitsbi/unlib. After I switched to Flutter, this works.

**Comment by pd4d10** [comment]
Is your device iOS or Android?

If it is Android, then probably related to #132

**Comment by gitsbi** [comment]
Yeah, it's Android 10, and you're probably right. Sorry for not having searched the list of open issues first. Feel free to close this as a dupe.

**Comment by pd4d10** [comment]
It doesn't matter. Just to get to the bottom of the problem
