### ISSUE TITLE
Select Parts of the written text when writing an issue

### ISSUE THREAD

**Issue by Quantenzitrone** [git-touch/git-touch#214]
It is possibele to select a single word or sentence of a text, in every normal app on android. On GitTouch there is only the possibility to copy or select the whole text.

**Comment by shreyas1599** [comment]
@Quantenzitrone do you mean this? It seems possible

![image](https://user-images.githubusercontent.com/28999492/121318809-3847be00-c929-11eb-8b1b-5328ad8e8c47.png)

**Comment by Quantenzitrone** [comment]
@shreyas1599 It doesn't work for me. When I long click a word, it just asks me if I want to paste or select all.

**Comment by shreyas1599** [comment]
@Quantenzitrone  which version of android are you using?

**Comment by Quantenzitrone** [comment]
@shreyas1599 Android 8.0.0

**Comment by shreyas1599** [comment]
@Quantenzitrone I tried it on Android 8.0.0 as well. Seems to be working fine. Did uninstalling and reinstalling not work?

**Comment by Quantenzitrone** [comment]
Idk man.
At first I wasnt able to log into my GitHub with GitTouch. I solved this by making a personal token to my GitHub for GitTouch.
Recently I received an update to Android 8.1. for my device. Still no change.
Idk if that matters but I use a custom ROM without Google Services.
