### ISSUE TITLE
main.dart.js file not found

### ISSUE THREAD

**Issue by Lukas-Batema** [git-touch/git-touch#216]
When working on a remodel of the web version, I came across this error right away in the js console. I do not know if it causes this, but it shows a blank page instead of what shows on the live site. Here are a few screenshots for reference...
___
![Screenshot 2021-03-19 19 11 41](https://user-images.githubusercontent.com/55695493/111850626-33094300-88e7-11eb-83d1-026d3244c1b9.png)
![Screenshot 2021-03-19 19 11 32](https://user-images.githubusercontent.com/55695493/111850629-343a7000-88e7-11eb-8a14-d5492d62285e.png)
#### These first two show the js console logs for the live site, which they all generally complain about the main.dart.js file missing.
___
![Screenshot 2021-03-19 19 11 15](https://user-images.githubusercontent.com/55695493/111850630-356b9d00-88e7-11eb-89c6-05bd394079a6.png)
![Screenshot 2021-03-19 19 10 35](https://user-images.githubusercontent.com/55695493/111850631-36043380-88e7-11eb-857d-88636f16b6a0.png)
#### The next two above are the same error on the web server shown in two different forms... a notification and in the console.
___
![Screenshot 2021-03-19 19 09 32](https://user-images.githubusercontent.com/55695493/111850633-37356080-88e7-11eb-8969-543a004c9d93.png)
#### The next one above shows the blank page which may be the outcome of the error.
___
![Screenshot 2021-03-19 19 09 22](https://user-images.githubusercontent.com/55695493/111850634-37356080-88e7-11eb-820b-75a3877085cd.png)
#### This last one shows why the thesis from the previous image and caption is not logical, as it is working on the live site. I still do think it is the outcome though...
___
Anyways, thanks for taking the time to read this!

**Comment by shreyas1599** [comment]
@Lukas-Batema which version of flutter are you using?

**Comment by Lukas-Batema** [comment]
> @Lukas-Batema which version of flutter are you using?

I do not know, which probably means I am not using it :/

**Comment by shreyas1599** [comment]
Right. How did you run it in the browser without flutter?

**Comment by Lukas-Batema** [comment]
> Right. How did you run it in the browser without flutter?

I used an IDE with a web server

**Comment by shreyas1599** [comment]
Oh. You're supposed to run it using flutter. 
`flutter run -d chrome`

**Comment by Lukas-Batema** [comment]
> Oh. You're supposed to run it using flutter.
> `flutter run -d chrome`

Yeah, I realize that now.

**Comment by shreyas1599** [comment]
>  Wait, what about the live site complaining about the missing file?

It's generated by flutter when you run `flutter run -d chrome`

**Comment by Lukas-Batema** [comment]
> > Wait, what about the live site complaining about the missing file?
> 
> It's generated by flutter when you run `flutter run -d chrome`

Ah, okay. Understandable now.
