### ISSUE TITLE
[FR] Open link in GitTouch

### ISSUE THREAD

**Issue by FunctionalHacker** [git-touch/git-touch#234]
Android has support for adding a list of suppported links by apps. This enables the user to click a link in their web browser and it resulting the link opening in the application.

For example, you could click [this link](https://github.com/git-touch/git-touch/issues/234) in your web browser to open this issue in GitTouch.

It comes to mind that the nature of GitTouch makes this a bit harder to implement. We would have to update the list of supported links as the user adds instances of eg. Gitea and GitLab. We would also have to handle switching accounts as needed.

[Android documentation](https://developer.android.com/training/app-links)
[Flutter documentation](https://flutter.dev/docs/development/ui/navigation/deep-linking)

**Comment by shreyas1599** [comment]
Being tracked in #60
