### ISSUE TITLE
Can't login to GitHub via OAuth

### ISSUE THREAD

**Issue by qwerty287** [git-touch/git-touch#236]
As the title says - if I try it, the web browser redirects to Gittouch and nothing happens.

**Comment by iBelow** [comment]
+1
on iOS after login via OAuth -> nothing happens

**Comment by qwerty287** [comment]
I don't use iOS, so it's also on Android

**Comment by pd4d10** [comment]
Could you please check the result of https://api.github.com/

**Comment by iBelow** [comment]
> Could you please check the result of https://api.github.com/

`{
  "current_user_url": "https://api.github.com/user",
  "current_user_authorizations_html_url": "https://github.com/settings/connections/applications{/client_id}",
  "authorizations_url": "https://api.github.com/authorizations",
  "code_search_url": "https://api.github.com/search/code?q={query}{&page,per_page,sort,order}",
  "commit_search_url": "https://api.github.com/search/commits?q={query}{&page,per_page,sort,order}",
  "emails_url": "https://api.github.com/user/emails",
  "emojis_url": "https://api.github.com/emojis",
  "events_url": "https://api.github.com/events",
  "feeds_url": "https://api.github.com/feeds",
  "followers_url": "https://api.github.com/user/followers",
  "following_url": "https://api.github.com/user/following{/target}",
  "gists_url": "https://api.github.com/gists{/gist_id}",
  "hub_url": "https://api.github.com/hub",
  "issue_search_url": "https://api.github.com/search/issues?q={query}{&page,per_page,sort,order}",
  "issues_url": "https://api.github.com/issues",
  "keys_url": "https://api.github.com/user/keys",
  "label_search_url": "https://api.github.com/search/labels?q={query}&repository_id={repository_id}{&page,per_page}",
  "notifications_url": "https://api.github.com/notifications",
  "organization_url": "https://api.github.com/orgs/{org}",
  "organization_repositories_url": "https://api.github.com/orgs/{org}/repos{?type,page,per_page,sort}",
  "organization_teams_url": "https://api.github.com/orgs/{org}/teams",
  "public_gists_url": "https://api.github.com/gists/public",
  "rate_limit_url": "https://api.github.com/rate_limit",
  "repository_url": "https://api.github.com/repos/{owner}/{repo}",
  "repository_search_url": "https://api.github.com/search/repositories?q={query}{&page,per_page,sort,order}",
  "current_user_repositories_url": "https://api.github.com/user/repos{?type,page,per_page,sort}",
  "starred_url": "https://api.github.com/user/starred{/owner}{/repo}",
  "starred_gists_url": "https://api.github.com/gists/starred",
  "user_url": "https://api.github.com/users/{user}",
  "user_organizations_url": "https://api.github.com/user/orgs",
  "user_repositories_url": "https://api.github.com/users/{user}/repos{?type,page,per_page,sort}",
  "user_search_url": "https://api.github.com/search/users?q={query}{&page,per_page,sort,order}"
}`

**Comment by qwerty287** [comment]
Same here

**Comment by qwerty287** [comment]
I tried to get the logs via adb logcat, and it returns an error, see below
```
2021-05-15 17:22:16.956 24039-24064/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
    Receiver: null
    Tried calling: []("viewer")
    #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51)
    #1      AuthModel.loginWithToken (package:git_touch/models/auth.dart:138)
    <asynchronous suspension>
    #2      AuthModel._onSchemeDetected (package:git_touch/models/auth.dart:120)
    <asynchronous suspension>
```
If you need more logs, I can try to get them, but I can't guarantee this.

**Comment by pd4d10** [comment]
Should have been fixed in the latest v1.12.4. Could you please help to confirm?

The iOS updates may be a little later due to the review process.

**Comment by qwerty287** [comment]
Yes it's working on my device
Thanks!

**Comment by pd4d10** [comment]
> The iOS updates may be a little later due to the review process.

Should be landed. Closing. Thanks for your reports!

**Comment by michaelblyons** [comment]
F-droid still has the version that is broken.
