### ISSUE TITLE
组织查看empty

### ISSUE THREAD

**Issue by hellotyty** [git-touch/git-touch#245]
组织查看empty

**Comment by shreyas1599** [comment]
@hellotyty can you give an example of where this occurs? You've to change the visibility of being part of the organization to "public" for it to appear in the organisation tab

**Comment by hellotyty** [comment]
Thanks~This problem was solved when i changed the visibility "public".         
            
                
                    
                            
                                
                            
                            
                                tyty2017
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        在2021年06月12日 15:12，Shreyas Thirumalai 写道： 
@hellotyty can you give an example of where this occurs? You've to change the visibility of being part of the organization to "public" for it to appear in the organisation tab

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/git-touch/git-touch/issues/245#issuecomment-860012802",
"url": "https://github.com/git-touch/git-touch/issues/245#issuecomment-860012802",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
