### ISSUE TITLE
Scrollbar appears in wrong place on profile view when scrolling contribution graph

### ISSUE THREAD

**Issue by phillipthelen** [git-touch/git-touch#37]
Instead of appearing over/directly under the graph, the scrollbar appears on the bottom of the view as seen in the screenshot. Not sure if this also happens on Android.

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-02-12 at 10 55 46](https://user-images.githubusercontent.com/298062/74323849-70b3a800-4d86-11ea-902b-a3ebacfbdaf2.png)

**Comment by shreyas1599** [comment]
Happens on Android as well. I tried finding a way to hide the scrollbar but could not find a way to do so. I even tried changing widgets but the scrollbar always sticks to the bottom.
