### ISSUE TITLE
Do not reload screen on Android bottom tab switch

### ISSUE THREAD

**Issue by pd4d10** [git-touch/git-touch#42]
Feedback from email

> Every time when I switch tab, from me to News, or other tabs. It will resend request, sometimes it’s so slowly and will use too much Cellular Data, would you please add a cache to save some data?

**Comment by pd4d10** [comment]
It is the default behavior of the built-in Material Scaffold widget. Perhaps we could do something to avoid it.

**Comment by anticafe** [comment]
I'm not sure if this article is helpful to let the tabs persistent: https://medium.com/fluttervn/making-bottom-tabbar-with-flutter-5ff82e8defe0
