### ISSUE TITLE
[Android] App loads in light mode always

### ISSUE THREAD

**Issue by shreyas1599** [git-touch/git-touch#50]
Even if dark mode has been set, the app starts in light mode and then immediately switches to dark mode. 

Attaching pictures for reference:

![photo_2020-04-08_01-00-58](https://user-images.githubusercontent.com/28999492/78711339-6e0fa200-7934-11ea-9fac-397e4e8695bd.jpg)
![photo_2020-04-08_01-01-01](https://user-images.githubusercontent.com/28999492/78711346-710a9280-7934-11ea-967f-c254d096e921.jpg)

**Comment by shreyas1599** [comment]
For some reason, it works now. I think the splash screen(which is white) and the home page were loading on top of each other or something of the sort.  I'm closing this issue. On another note, @pd4d10 I think it'd be a good idea to have a splash screen. What do you think? I can add it.

**Comment by pd4d10** [comment]
> it'd be a good idea to have a splash screen

Agreed
