### ISSUE TITLE
Return to home once tab in bottom bar is clicked

### ISSUE THREAD

**Issue by shreyas1599** [git-touch/git-touch#54]
In the `Cupertino` theme while navigating within a tab bar, on clicking the bottom bar when inside a particular bottom bar item, we could return to the home screen. This is especially useful when you are inside a repository and have to go back several times to return to the home screen. 

## Example:

This is home.

![image](https://user-images.githubusercontent.com/28999492/79014559-c6d77880-7b88-11ea-8430-41503b66cd11.png)

I'm inside the issues of a repository and want to back to news home. If I click on the News tab it takes me back to the starting screen(previous image).

![image](https://user-images.githubusercontent.com/28999492/79014523-b32c1200-7b88-11ea-93a2-350c834981fc.png)

In `Material` bottom bar is not visible, so we could do it only for `Cupertino`.

**Comment by pd4d10** [comment]
Good point. I think we could do this!
