### ISSUE TITLE
Add Organizations of a user

### ISSUE THREAD

**Issue by shreyas1599** [git-touch/git-touch#58]
Currently, the organizations a user belongs to is not displayed. Also, if a repo belongs to an organization instead of an individual as is the case with this repo, the link of the organization won't work. 

So we need an organization screen and on the profile page, the list of organizations the user is a part of. Where do you think we could place it? (It'd just be a row(s) of profile pictures) 

![image](https://user-images.githubusercontent.com/28999492/79053973-fce72c00-7c5e-11ea-829a-9387965ffad6.png)

Below the yellow line or above the contributions graph or anywhere else?

**Comment by pd4d10** [comment]
I'm not sure. Seems both would be OK?

**Comment by shreyas1599** [comment]
@pd4d10 I need some help. I'm trying to add the organization connection in `gh_user.graphql`. Under `repositoryOwner` and inside `... on User` is where I'm trying to place it. But for some reason it affects the results of `... onOrganization` in `gh_user.dart`. Am I doing anything wrong?

**Comment by pd4d10** [comment]
It seems an issue of the artemis lib: https://github.com/comigor/artemis/issues/18

I tried to upgrade its version before but got another problem: https://github.com/comigor/artemis/issues/63#issuecomment-590172267

**Comment by shreyas1599** [comment]
Alright. Also in the `org_repo`
screen some organizations have to enable permission for us to be able to fetch details. For example, I'm able to view the Google organization but not the git touch organization (it is stuck on loading forever). Do you think if would be good to add a timeout option and tell display a pop-up telling the user about this? But as far as I know you are already displaying an error message if an error occurs. Still no error message pops up. Maybe because we should add a timeout feature?

**Comment by pd4d10** [comment]
I'm not sure if the permission you mentioned is related to this:

https://github.com/git-touch/git-touch/blob/805f065def16e008d65d5fc230eb1a212df93319/lib/screens/gh_org_repos.dart#L10-L15

We have changed it from GraphQL to RESTful API to avoid the access restriction.

**Comment by pd4d10** [comment]
> . Maybe because we should add a timeout feature?

Agreed. We could have one.

**Comment by shreyas1599** [comment]
> I'm not sure if the permission you mentioned is related to this:
> 
> https://github.com/git-touch/git-touch/blob/805f065def16e008d65d5fc230eb1a212df93319/lib/screens/gh_org_repos.dart#L10-L15
> 
> We have changed it from GraphQL to RESTful API to avoid the access restriction.

Yeah, I saw this but for some reason it still doesn't load even though the organization is public( I'm talking about git-touch). Timeout sounds like a hacky fix for now. Doesn't point to the underlying problem.
