### ISSUE TITLE
Figure out a way to do beta testing

### ISSUE THREAD

**Issue by pd4d10** [git-touch/git-touch#61]
The release period is long and the features we added might not be fully tested.

* iOS: TestFlight
* Android: ?

**Comment by shreyas1599** [comment]
I'm not sure but for Android wouldn't you have to do something like this: [Open Beta](https://support.google.com/googleplay/android-developer/answer/3131213?hl=en#open_beta)?

**Comment by shreyas1599** [comment]
We could also add a link to the beta in settings. While at it, do you think it'd be good to add an FAQ for commonly faced permission problems? You also said you'd like to include ways to help the user find out about the long press in #36? We could add that as well. Should I open a separate issue for this?

**Comment by pd4d10** [comment]
> add an FAQ for commonly faced permission problems

is it meant to be in README or in the app?

**Comment by shreyas1599** [comment]
I think app would be better

**Comment by pd4d10** [comment]
> I think app would be better

OK, get it. Let's open a new issue for this feature.

**Comment by shreyas1599** [comment]
Any plans on doing this soon?

**Comment by pd4d10** [comment]
Trying to make it work this week...

**Comment by pd4d10** [comment]
Android: https://play.google.com/apps/testing/io.github.pd4d10.gittouch

**Comment by aseef17** [comment]
> Android: https://play.google.com/apps/testing/io.github.pd4d10.gittouch

Hey @pd4d10 
When can we expect the application to be released in TestFlight ?

**Comment by pd4d10** [comment]
@aseef17 The review process is just finished.

https://testflight.apple.com/join/hAYijLr5

**Comment by pd4d10** [comment]
Added to README: https://github.com/git-touch/git-touch#installation

I'm going to close this issue. Feel free to discuss it here if there are other issues
