### ISSUE TITLE
Support for gists

### ISSUE THREAD

**Issue by shreyas1599** [git-touch/git-touch#66]
Add user's gists in the profile section.

**Comment by shreyas1599** [comment]
@pd4d10 I could use some help. Consider the json output for getting [gists](https://api.github.com/users/shreyas1599/gists).

`Files` is another json and not a list. I'm having trouble serializing this. The Spinlocklabs `github.dart` declares it as a list which is wrong and results in an error. I've opened an issue there. This is what I've done for now. 

```
class GithubGistsItem {
  String id;
  String description;
  bool public;
  Map<String, GistFiles> files;
  GithubEventUser owner;
  List<dynamic> get fileNames {
    var filenames = [];
    files.forEach((String key, GistFiles value) {
      filenames.add(value);
    });
    return filenames;
  }

  DateTime createdAt;
  DateTime updatedAt;

  GithubGistsItem();
  factory GithubGistsItem.fromJson(Map<String, dynamic> json) =>
      _$GithubGistsItemFromJson(json);
} 
```

But making `fileNames`dynamic is creating problems everywhere and I'm not sure if this is the right way to serialize it. For instance, I am unable to use the `ObjectTree` widget. I have created another widget file and solved the problem but I think re-using the `ObjectTree` widget is a better way to go. The error is something to do with fileNames being dynamic. Any help is appreciated. Thanks.

**Comment by pd4d10** [comment]
What's the error message (or error stack)?

**Comment by shreyas1599** [comment]
`type 'MappedListIterable<dynamic, dynamic>' is not a subtype of type 'Iterable<ObjectTreeItem>'`

**Comment by pd4d10** [comment]
How about using `files.values()`?

**Comment by pd4d10** [comment]
Or `files.entries()` if you want the key too

**Comment by shreyas1599** [comment]
Doesn't work. Still getting the same error. If I try to use `files.values` I'm getting the same error as above. But for `fileNames.values` the error is:

`Class 'List<dynamic>' has no instance getter 'values'. Receiver: Instance(length:1) of '_GrowableList'. Tried calling: values`

**Comment by pd4d10** [comment]
Oh, my mistake. `values` and `entries` are getters, not methods.

**Comment by pd4d10** [comment]
Perhaps you could submit a WIP pull request so I could help to check it.

**Comment by shreyas1599** [comment]
A WIP pull request is a draft pull request right?
