### ISSUE TITLE
Add the Search tab for GitLab

### ISSUE THREAD

**Issue by AndreiJirohHaliliDev2006** [git-touch/git-touch#67]
Roaming around GitLab with GitTouch is hard, can you add the Search tab for GitLab?

**Comment by shreyas1599** [comment]
@pd4d10 Can I do this? Per [this](https://docs.gitlab.com/ee/api/search.html), there are many scopes, but I should do only projects, issues and users, similar to github right? Also, do you have any intent in migrating to graphql?(this one though can only be done through REST)

**Comment by pd4d10** [comment]
@shreyas1599 Sure, that would be great.

**Comment by AndreiJirohHaliliDev2006** [comment]
> @pd4d10 Can I do this? Per [this](https://docs.gitlab.com/ee/api/search.html), there are many scopes, but I should do only projects, issues, and users, similar to GitHub right? Also, do you have any intent in migrating to GraphQL? (this one though can only be done through REST)

@shreyas1599 So, in the global search, we only pull `projects`, `users`, and issues` s scopes to search. And speaking of GraphQL, maybe we can ask GitLab about migrating to GraphQL like what GH does?

**Comment by shreyas1599** [comment]
> And speaking of GraphQL, maybe we can ask GitLab about migrating to GraphQL like what GH does?

Yeah, they have graphql support only for a few API's. They're slowly adding them, I think.

**Comment by pd4d10** [comment]
Hi, @AndreiJirohHaliliDev2006 , are you using iOS or Android devices?

Thanks to the PR by @shreyas1599 , Android beta version has been released: https://play.google.com/apps/testing/io.github.pd4d10.gittouch

iOS test flight version is being reviewed. I'll update the link once it's finished.

For detail see this issue: https://github.com/git-touch/git-touch/issues/61

Thanks for your feedback!

**Comment by AndreiJirohHaliliDev2006** [comment]
> Hi, @AndreiJirohHaliliDev2006 , are you using iOS or Android devices?
> 
> Thanks to the PR by @shreyas1599 , Android beta version has been released: https://play.google.com/apps/testing/io.github.pd4d10.gittouch
> 
> iOS test flight version is being reviewed. I'll update the link once it's finished.
> 
> For detail see this issue: #61
> 
> Thanks for your feedback!

I am using Android 4.4.3. I'll join the beta testers squad soon as I am back on my phone. Thanks again, @pd4d10.
