### ISSUE TITLE
Files changed screen in a PR

### ISSUE THREAD

**Issue by shreyas1599** [git-touch/git-touch#74]
Hi @pd4d10,
So I'm trying to add a `Files Changed Screen` instead of redirecting to the web. This is an example [response](https://api.github.com/repos/git-touch/git-touch/pulls/72/files).

The modified text is in `patch`.

`\n` followed by + indicates an addition and similarly `\n` followed by - indicates deletion.

My idea is to split it on `\n` and every list item that starts with a `+` I'm thinking of wrapping with Text with green color and similarly red color for `-`.  Is this a right approach or would you suggest an alternative way? 

Also I'm unable to understand the starting portion of the patch. I know it has something to do with the line number. Take the first item of the example [response](https://api.github.com/repos/git-touch/git-touch/pulls/72/files)
`@@ -313,3 +313,15`. 

Do you have an idea? 

I'll put a list of files with a drop-down for every file which will expand to display the changes.

**Comment by pd4d10** [comment]
Perhaps `flutter_highlight` package could do some help:

```dart
HighlightView(
  code: '', // The diff code
  language: 'diff',
)
```
