### ISSUE TITLE
Blank profile screen for BitBucket

### ISSUE THREAD

**Issue by aseef17** [git-touch/git-touch#79]
The user section (Team/Me) section just shows a blank screen for a BitBucker user

![image](https://user-images.githubusercontent.com/26878414/80848590-5bd20c80-8c31-11ea-822f-ac01dd6f0d51.png)

**Comment by pd4d10** [comment]
Oh, it's wired. Is this BitBucket instance https://bitbucket.org or self-hosted? Could you please provide your BitBucket username?

**Comment by aseef17** [comment]
That’s the bitbucket instance
My username is aseef_boilerplate

**Comment by shreyas1599** [comment]
@pd4d10 I just noticed this as well. Attaching a screenshot. Must be because of no avatar.

![image](https://user-images.githubusercontent.com/28999492/80855730-2f35e900-8c61-11ea-905f-3d8507c5c9b1.png)

**Comment by aseef17** [comment]
> @pd4d10 I just noticed this as well. Attaching a screenshot. Must be because of no avatar.
> 
> 
> 
> EDIT: I just compared the release version on the play store with the latest mater branch. Master branch works fine. Problem with the release. 
> 
> 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/28999492/80855730-2f35e900-8c61-11ea-905f-3d8507c5c9b1.png)
> 
> 
> 
> 

I don’t suppose that’s the problem. I added a profile image, removed and added my account again but I still have the same blank grey screen

**Comment by shreyas1599** [comment]
@aseef17 Are you using the release version on play/app store or have you built it by yourself? As I've mentioned in my comment, the latest master branch works fine while there's a problem with the release.

**Comment by aseef17** [comment]
> @aseef17 Are you using the release on play/app store or have you built it by yourself? As I've mentioned in my comment, the latest master branch works fine while there's a problem with the release.

Using the release version from App Store. I wouldn’t mind side loading but it’s just too much of a hassle to refresh Apple app ID every 7 days or the app becomes non-functional

**Comment by shreyas1599** [comment]
@pd4d10 is planning to release it on test flight soon. You could use that when it's available.

**Comment by shreyas1599** [comment]
@pd4d10 I just checked. I'm afraid this error still exists on the android beta release.

**Comment by shreyas1599** [comment]
Just checked. This is the error. I got a positive response when I used my accountID instead of my username. Seems like we should add accountId to `Account`.

**Comment by aseef17** [comment]
@pd4d10 
This issue still occurs in the beta release on TestFlight. 
You should check out PR made by @shreyas1599
