### ISSUE TITLE
Error using already used personal token on gitlab

### ISSUE THREAD

**Issue by shreyas1599** [git-touch/git-touch#82]
I didn't realise that you cannot use the same token for the same app on different devices for gitlab. When a wrong token is used, as expected a 404 error is returned. But when you use an already used token the following error occurs. The only way to resolve this is to uninstall and re-install the app. Probably a gitlab bug but we should handle the error better and allow the user to enter a different token.

![image](https://user-images.githubusercontent.com/28999492/81400033-d4f9c400-9149-11ea-812e-948521dd6c17.png)

**Comment by pd4d10** [comment]
I could not reproduce it. If an invalid token submitted:

![image](https://user-images.githubusercontent.com/9524411/81464927-8ce5aa80-91f8-11ea-8c6a-147027343433.png)

**Comment by shreyas1599** [comment]
Not an invalid token. Use a token which was already used on another device. Should I share my token here?

**Comment by pd4d10** [comment]
I don't think so. That would be unsafe.

**Comment by shreyas1599** [comment]
You could try the token you used on an actual device on a simulator or the other way round?

**Comment by pd4d10** [comment]
I commented on the PR you submitted. We could discuss there
