### ISSUE TITLE
Option to make account primary

### ISSUE THREAD

**Issue by shreyas1599** [git-touch/git-touch#84]
@pd4d10 Doesn't seem too hard. I'd just have to use a `ReorderableList`. I'll open a PR for this if it's alright with you.

**Comment by shreyas1599** [comment]
I think it's better to have an option to make an account primary so it opens by default while opening the app. (the intention of using reorder able list was to move the frequently used accounts to the top). Making an account primary seems a better way to do it.

**Comment by shreyas1599** [comment]
Looks like `auth.activeAccount` already solves this. But it is not persistent. Login screen reopens if you force close and open the app. Should we just write it into shared prefs? 

_(Eg: On popular apps that support multiple accounts, opening the last used account is the way its done instead of asking the user to select from the list of accounts)_

**Comment by pd4d10** [comment]
> opening the last used account

OK, I think it's a good idea
