### ISSUE TITLE
Error displaying repo with 0 files

### ISSUE THREAD

**Issue by shreyas1599** [git-touch/git-touch#99]
An error occurs (see image below) when the repo is initialized with zero files. I created a public repo - [test](https://github.com/shreyas1599/test) to confirm this was not only caused for private repos(I found the problem while opening a private repo). The error is caused by [fetchContributors](https://github.com/git-touch/git-touch/blob/1276957b2d14ad93b3762bb109a457711085d978/lib/screens/gh_repo.dart#L54). For example: https://api.github.com/repos/shreyas1599/test/stats/contributors does nothing. Does not even return an error message. I tried using the debugger and it returned an exception on [this line of github.dart](https://github.com/SpinlockLabs/github.dart/blob/3c88457815f3013fcbf54032567dca3815f3953e/lib/src/common/github.dart#L278) of SpinlockLabs. 

I'm thinking there's no response and `jsonDecode` is throwing an error because nothing is returned by the request. Could this be the error or am I missing something? 

![image](https://user-images.githubusercontent.com/28999492/90339050-d1f55600-e00b-11ea-821a-e61ca58e71a6.png)

**Comment by pd4d10** [comment]
> I'm thinking there's no response and jsonDecode is throwing an error because nothing is returned by the request

Yeah, it seems so. Perhaps we should manually catch this error in this case.
